code/examples/22-jan/grocery-22jan/grocery/urls.py
from django.urls import path

from . import views

app_name = 'grocery'

urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('complete/<int:pk>/', views.complete, name='complete'),
    path('delete/<int:pk>/', views.delete, name='delete')
]

code/examples/22-jan/grocery-22jan/grocery_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('grocery.urls'))
]

code/examples/22-jan/grocery-22jan/grocery/models.py
from django.db import models

class GroceryItem(models.Model):
    description = models.CharField(max_length=200)
    created_date = models.DateTimeField()
    completed_date = models.DateTimeField(null=True, blank=True)
    completed = models.BooleanField()

    def __str__(self):
        return self.description

code/examples/22-jan/grocery-22jan/grocery/views.py
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from django.http import HttpResponseRedirect
from django.urls import reverse

from .models import GroceryItem

def index(request):
    completed_items = GroceryItem.objects.filter(completed=True).order_by('-completed_date')
    incomplete_items = GroceryItem.objects.filter(completed=False).order_by('created_date')
    context = {
        'completed_items': completed_items,
        'incomplete_items': incomplete_items
    }
    return render(request, 'grocery/index.html', context)

def new(request):
    description = request.POST['description']
    GroceryItem.objects.create(description=description, created_date=timezone.now(), completed=False)
    return HttpResponseRedirect(reverse('grocery:index'))

def complete(request, pk):
    item = get_object_or_404(GroceryItem, pk=pk)
    # if item.completed:
    #     item.completed = False
    #     item.completed_date = None
    # else:
    #     item.completed = True
    #     item.completed_date = timezone.now()
    item.completed = False if item.completed else True
    item.completed_date = timezone.now() if item.completed else None
    item.save()
    return HttpResponseRedirect(reverse('grocery:index'))

def delete(request, pk):
    item = get_object_or_404(GroceryItem, pk=pk)
    item.delete()
    return HttpResponseRedirect(reverse('grocery:index'))

code/examples/22-jan/grocery-22jan/grocery/templates/grocery/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Grocery List</title>
</head>
<body>
    <h1>Grocery List</h1>

    <form action="{% url 'grocery:new' %}" method="post">
        {% csrf_token %}
        <label for="description-input">Description:</label>
        <input type="text" name="description" id="description-input" required>
        <input type="submit" value="Add Item">
    </form>

    <h2>Incomplete</h2>
    <ul>
    {% for item in incomplete_items %}
        <li>{{ item.description }}
            <form action="{% url 'grocery:complete' item.pk %}" method="post">
                {% csrf_token %}
                <input type="submit" value="Complete">
            </form>
            <form action="{% url 'grocery:delete' item.pk %}" method="post">
                {% csrf_token %}
                <input type="submit" value="Delete">
            </form>
        </li>
    {% endfor %}
    </ul>

    <h2>Completed</h2>
    <ul>
    {% for item in completed_items %}
        <li>{{ item.description }}
            <form action="{% url 'grocery:complete' item.pk %}" method="post">
                {% csrf_token %}
                <input type="submit" value="Mark incomplete">
            </form>
            <form action="{% url 'grocery:delete' item.pk %}" method="post">
                {% csrf_token %}
                <input type="submit" value="Delete">
            </form>
        </li>
    {% endfor %}
    </ul>
</body>
</html>